Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [1]:
import numpy as np

def vader_class(vector, n, increasing = False):
    if not increasing:
        output_matrix = np.array([x**(n-1-i) for x in vector for i in range(n)]).reshape(vector.size,n)
    elif increasing :
        output_matrix = np.array([x**i for x in vector for i in range(n)]).reshape(vector.size, n)
    
    return output_matrix

print("---------------- Output------------------------\n\n")

a = np.array([1,2,3,4,5])
no_col_op = 3
op_desc_order = vader_class(a,no_col_op ,False)
op_asc_order = vader_class(a,no_col_op ,True)

print("The input array is:",a,"\n")
print("Number of columns in output matrix should be:",no_col_op,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",op_desc_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",op_asc_order,"\n")

---------------- Output------------------------


The input array is: [1 2 3 4 5] 

Number of columns in output matrix should be: 3 

Vander matrix of the input array in decreasing order of powers:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

Vander matrix of the input array in increasing order of powers:

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 



### Another way

In [2]:
a = np.array([1,2,3,4,5])
no_col_op = 3

Desc_Order = np.vander(a, no_col_op, increasing=False)
Asc_Order = np.vander(a, no_col_op, increasing=True)

print("The input array is:",a,"\n")
print("Number of columns in output matrix should be:",no_col_op,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",Desc_Order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",Asc_Order,"\n")

The input array is: [1 2 3 4 5] 

Number of columns in output matrix should be: 3 

Vander matrix of the input array in decreasing order of powers:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

Vander matrix of the input array in increasing order of powers:

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 



# Problem Statement 2:

In [3]:
numbers = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
window_size = 3

i = 0
moving_averages = []
while i < len(numbers) - window_size + 1:
    this_window = numbers[i : i + window_size]


    window_average = sum(this_window) / window_size
    moving_averages.append(window_average)
    i += 1

print("Output of moving_average :", moving_averages)

Output of moving_average : [5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
